services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=gymdev
      - DB_PASS=1234
      - DB_NAME=vivaemmovimento
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    container_name: postgres
    image: postgres:alpine
    command: -c password_encryption=md5
    environment:
      POSTGRES_DB: vivaemmovimento
      POSTGRES_USER: gymdev
      POSTGRES_PASSWORD: "1234"
      POSTGRES_HOST_AUTH_METHOD: md5
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
  node_modules:
