POST  http://localhost:3000/clientes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlhdCI6MTcxNTgxMzQ2MSwiZXhwIjoxNzE1ODI3ODYxfQ.S-hllY9deuncUpylzZbTqP9jd_CnVfdc43Z30FZT9Cw

{
    "name": "Tsfs",
    "phone": "123-456-7890",
    "birthdate": "1980-05-09",
    "enrollmentDate": "2021-09-01",
    "exitDate": null,
    "dueDay": 30,
    "active": true,
    "lastPaymentDate": null,
    "paymentStatus": false
}
