GET http://localhost:3000/clientes HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MTQ4NTQ5NjMsImV4cCI6MTcxNDg2OTM2M30.oX2WcVVx_hJhOdPFDElX2yFxoB0I3H5o8N8Px1D2qsA

