GET  http://localhost:3000/mes/usuario HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRldiIsImlhdCI6MTcxNjI1NjM2OCwiZXhwIjoxNzE2MjcwNzY4fQ.j8iRMzxMXBevudTGSCP96m2TgwIdcvKnGVXsIngzSyU
