POST http://localhost:3000/clientes/send HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpYXQiOjE3MTUyMjI2MzAsImV4cCI6MTcxNTIzNzAzMH0.Xpm1Y_VGvM8sD2-al0CMnSaNUQhRXRFHJGa5cTpGfI4


